#!/bin/bash

# This is Stage 1 of a program to scrape the blizard webpage and grab achevements, and Battle pet data
# Project "Ice-Melt" by Andrew Malone to automate cross refrancing toons
# Copyright (C) Andrew Malone 2015

# $1 = File Name
# $2 = Realm Name
# $3 = Temp SQL file
# $4 = MySQL User
# $5 = MySQL password
# $6 = MySQL database
# $7 = MySQL HOST
# $8 = MySQL PORT

#echo "Processing file $1"
#echo "Building Mysql table icemelt.guilds"
#echo "Realm Name $2."
#echo "Output saved to $3"

sed 's:,:\n:g' $1 |
grep "\"name\":" |
sed '{s:\"name\"\:::g; s:\"::g; s:\\::g}' |
awk -f guild_inserts.awk |
sed 's:REALM_NAME:'$2':' |
sed 's:"REGION_ID:$$9':' | #replace the REGION_ID with the actual Identifier
tee -a $3 |
mysql --user=$4 --password=$5 --host=$7 --port=$8 $6

# step 1 	sed replaces EVERY , with a newline
# step 2 	grep for "name" as we only care about the realm names from this file
# step 3.1 	strip "name": off the front of the line
# step 3.2 	strip out the " surounding the guild name
# step 3.3 	strip out the \'s this causes an error with MySQL (can we escape them?)
# step 5 	pull our AWK script and build SQL statements
# step 6 	replace REALM_NAME with our provided $2 value from user (should be a realm name however we are unable to check)
# step 7 	TEE output appending to file $3
# step 8 	Run MySQL query inline with all provided information


## table structure of guilds
## GID Realm Guild

## Char database to link into guilds (as blizzard has made it possible for multiple Realms to hold a single guild only the GID above will be relivant)
## CID GID toon_name realm_name TimeStamp_updated
