#!/bin/bash

MYSELECT='SELECT `gid` FROM `chars` WHERE `toon_name` LIKE "'$1'";'

# this takes a single argument $1 a toon name this script will pull the GID of that toon and output the guild associated with it
# here we use the provided input after we process this into a MySQL command we call mysql and return the GID to cross refrance over to the guild
echo "Running Query"

# Optional output
echo $MYSELECT

echo ''

gid=$(echo $MYSELECT | mysql -u root icemelt | grep -v "gid")

GSELECT='SELECT `realm`,`guild` FROM `guilds` WHERE `index` ='$gid';'

echo "Running Cross Refrance for $1 GID found: $gid"
echo "Using Query: $GSELECT"

echo ''
echo $GSELECT | mysql -u root icemelt

# temp output section
#echo "Guild Number for toon $1 is $gid"
