CREATE USER 'icemelt'@'localhost' IDENTIFIED BY 'icemelt';
GRANT USAGE ON *.* TO 'icemelt'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE  ON `icemelt`.* TO 'icemelt'@'localhost';
FLUSH PRIVILEGES;
